# Generated by Django 6.1.1 on 2026-09-12 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('sub_title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('catergory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.catergory')),
            ],
        ),
    ]
